name: quran_mentor
description: "A new Flutter project."

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ^3.5.4

dependencies:
  bloc: ^8.1.4
  cupertino_icons: ^1.0.8
  dartz: ^0.10.1
  dio: ^5.7.0
  equatable: ^2.0.5
  firebase_analytics: ^11.3.4
  firebase_auth: ^5.3.2
  firebase_core: ^3.7.0
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.6
  flutter_launcher_icons: ^0.14.1
  flutter_local_notifications: ^18.0.0
  flutter_localizations:
    sdk: flutter
  flutter_native_splash: ^2.4.2
  flutter_phoenix: ^1.1.1
  flutter_sound: ^9.16.3
  flutter_spinkit: ^5.2.1
  flutter_svg: ^2.0.14
  flutter_tts: ^4.0.2
  flutter_widget_from_html_core: ^0.15.2
  fluttertoast: ^8.2.8
  get_it: ^8.0.2
  internet_connection_checker: ^1.0.0+1
  intl: ^0.19.0
  path_provider: ^2.1.5
  permission_handler: ^11.3.1
  record: ^5.2.0
  shared_preferences: ^2.3.3
  simple_animations: ^5.1.0
  speech_to_text: ^7.0.0
  validators: ^3.0.0

dev_dependencies:
  flutter_lints: ^4.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - lang/ar.json
    - lang/en.json
    - assets/loading-animated.gif
